pipeline:
  name: PetClinic Build Intelligence - V3
  identifier: PetClinic_Build_Intelligence_V3
  projectIdentifier: BY_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: YashwanthChowdary05
        build: <+input>
  stages:
    - stage:
        name: Build Stage
        identifier: Build_Stage
        description: "Builds Spring PetClinic with Gradle and TI Caching"
        type: CI
        spec:
          cloneCodebase: true
          # Goal 2: Enable Build Intelligence
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build with Gradle
                  identifier: Build_with_Gradle
                  spec:
                    connectorRef: <+input>
                    # Goal 1: Evaluate Build Tool Support (Gradle)
                    image: gradle:8.4-jdk17
                    shell: Sh
                    command: |-
                      # 'build' compiles code and runs tests
                      # --no-daemon is best practice for CI to save memory
                      ./gradlew build --no-daemon
                    
                    # Optional: Visualizes test results in Harness
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/build/test-results/**/*.xml"
